### ISSUE TITLE
Display about 1-2 seconds delayed

### ISSUE THREAD

**Issue by JsBergbau** [rene0/dcf77pi#29] opened 2018-03-24 17:31 UTC
Thanks for your great program. I've just set it up and noticed that there is about 1-2 seconds delay compared to a physical DCF77-clock and even data from here https://dcf77logs.de/live is about 1 seconds faster than the output of dcf77pi. Is something wrong with my setup? I've also noticed that there is a log file created but it stays empty...

PS: For raspberry you have to do 
`sudo apt-get install libncurses5-dev libncursesw5-dev libjson-c-dev`
before it compiles. And I only got it running by creating /etc/dcf77pi/config.json and starting it from the root working directory.

**Comment by rene0** [comment] 2018-03-25 11:40
I updated the instructions, thanks for the pointer.

**Comment by rene0** [comment] 2018-03-25 12:04
The 1.05 second delay you are experiencing is an artifact of the current reception algorithm, your setup is probably fine ;).  I plan to make the reception more "live" (see #4) but I first wanted to finish writing a bunch of unit tests (boring stuff first). 

The current reception algorithm listens to the radio signal and keeps a 50 ms buffer (also known as a 50 ms delay) to measure what the signal has been doing. Only if the algorithm has enough confidence that a new second has started (high signal), it will return the value of the previous second (0 or 1). This buffer is needed to compensate for random noise, especially from simple receivers like mine. This buffer causes the algorithm to only know that a new second has started 50 ms too late.

Although the polling frequency is set to 1000 Hz in the configuration file, the actual frequency is usually a bit less (943 Hz on my setup, the value shown as "realfreq") because the nanosleep() function which is used in between two polls only guarantees a minimal sleeping time. Because of this difference (6% in my case), the algorithm cannot compensate exactly for the 50 ms delay.

Regarding the 1 second delay, this might be a matter of perception. Currently dcf77pi displays the bit after it is fully received, instead of using a placeholder value and filling in the real value afterwards. The big number in parentheses after the minute value gives an estimate of the current second value.

**Comment by rene0** [comment] 2018-03-25 12:06
"I only got it running by creating /etc/dcf77pi/config.json and starting it from the root working directory." <-- can you show me the commands used to build (and install) the program and as which user? You can set the PREFIX value during *all* make commands to install it under PREFIX (see the README).

**Comment by JsBergbau** [comment] 2018-03-25 12:27
Thanks for your fast and detailed reply.

`This buffer is needed to compensate for random noise, especially from simple receivers like mine. This buffer causes the algorithm to only know that a new second has started 50 ms too late.`
It's intresting. I have two different modules one for 6 € and one for 14 €. Both have the same receiption quality and both have a lower reception quality than a DCF77 alarmclock with display for just 6 €. You can test this by bringing the charger station of your battery Toothbrush (Oral-B) at a distance of about 10 cm. dcf77pi makes a lot of errors, getting the time unusable. The alarm clock for 6 € even manages it at 8 cm distance to sync time correctly. Both antennas were directed at the same direction and the same height. The alarm clock was just in between the receiver antenna and the Oral-B charging station.

`Regarding the 1 second delay, this might be a matter of perception. Currently dcf77pi displays the bit after it is fully received, instead of using a placeholder value and filling in the real value afterwards. The big number in parentheses after the minute value gives an estimate of the current second value.`

Its even a 2 second delay. I hold the alarm clock right beside the display to compare the seconds. dcf77pi is 2 seconds behind the time displayed on the alarmclock. DCF77Live is one second behind (ok the data have to travel through the server and Internet). However if DCF77Pi syncronizes the time (dind't test this yet) correctly, its no problem for me.

`"I only got it running by creating /etc/dcf77pi/config.json and starting it from the root working directory." `
Can't really tell you, I've done it several times.
Mostly it was with user pi
"make"
and "make install"
Sometimes make install gave a premission error, so I did sudo make install.

When you tell me how to cleanup correctly, I'll give it a new try.

**Comment by rene0** [comment] 2018-03-25 13:44
> Its even a 2 second delay. 

No it's not, just compare it to your computer clock. I think your alarm clock is out of sync (can you test that by pulling out the battery/mains plug and power it on in a quiet place?). The last second of the minute is indeed skipped because that one has no pulse of its own (this is also part of #4). Regarding dcf77pi not getting the time correctly: if you start it with bad reception, then it will try its best but is refuses to accept untrustworthy results.

> Mostly it was with user pi

Hm, so we need to clean up a bit because of `sudo make install`:
- keep a safe copy of your config.json file in case it differs from the default
- find all instances of the dcf77pi binary (for example /bin/dcf77pi and /usr/bin/dcf77pi)
- clean up all these instances: `sudo make clean PREFIX=/` and `sudo make clean PREFIX=/usr`
-  figure out where you want to  install dcf77pi (e.g. /opt/github), then `make PREFIX=/opt/github` and `make install PREFIX=/opt/github` 
- ensure the installed config.json matches your preferences

**Comment by JsBergbau** [comment] 2018-03-25 15:08
> No it's not, just compare it to your computer clock. I think your alarm clock is out of sync (can you test that by pulling out the battery/mains plug and power it on in a quiet place?). 

Sorry you're right the clock was ahead 1 second (compared to 5 other clocks which were in sync). It is now almost perfect in sync with https://dcf77logs.de/live and dcf77pi still one second back. Or I am misinterpreting the data 
`summer 2018-03-25 Sun 16:43 (     24991 2.0000)  `
This "24" is for me the value of seconds or is it in reality 25 seconds, then they would be in sync.

> Hm, so we need to clean up a bit because of sudo make install:

OK I've cleaned up with find command. I've removed the complete directory and downloaded again to remove my modifications (and noticed something more, I'll comment in the log thread about it) In the docs is written

> To build and install the program into /usr/bin , the library into /usr/lib and the configuration file into /usr/etc/dcf77pi :

% make PREFIX=/usr
% sudo make install PREFIX=/usr

without sudo make install it always gives errors, so now I installed again with sudo and like above PREFIX=/usr
Now I don't need to run it from root directory anymore. However at the first start following error occured:
`json_object_from_file: error opening file /usr/etc/dcf77pi/config.json: No such file or directory`
So no config was created. After copying my saved config dcf77pi now works again.

**Comment by rene0** [comment] 2018-03-25 18:25
That `json_object_from_file error` is not very neat but indeed expected behavior. The installation script does install a `config.json.sample` into `/usr/etc/dcf77pi/` , perhaps it should also copy that to `config.json` in case it does not exist or show some better hints.

**Comment by rene0** [comment] 2018-03-25 18:32
> It is now almost perfect in sync with https://dcf77logs.de/live and dcf77pi still one second back. Or I am misinterpreting the data
`summer 2018-03-25 Sun 16:43 ( 24991 2.0000)`
This "24" is for me the value of seconds or is it in reality 25 seconds, then they would be in sync.

It is 24991 milliseconds, which is indeed the amount of time the program thinks has passed since the start of the minute, based upon adding the value of `total/realfreq` together to this 24991 each second.

**Comment by JsBergbau** [comment] 2018-03-25 19:30
Sorry, I couldn't interpret the number. Now everything makes sense and dcf77pi is perfectly in time. Sorry for bothering.
What does the 2.0000 mean?

**Comment by rene0** [comment] 2018-03-25 19:55
That 2.000 is what is code-wise known as the "cutoff" value. This is the length of the last bit of the minute (which is two pulses long) divided by the average pulse length. It was mostly used at some point to determine the lower bound for detecting the end of a minute.

**Comment by rene0** [comment] 2018-05-27 14:13
Closing this ticket, all open actions have been moved to their own tickets.

**Closed as completed by rene0** 2018-05-27 14:13 UTC
